image: bradrydzewski/go:1.3
script:
  - go get github.com/tools/godep
  - mkdir -p $GOPATH/src/github.com/Clever
  - ln -s `pwd` $GOPATH/src/github.com/Clever/redshifter
  - export AWS_ACCESS_KEY_ID=x
  - export AWS_SECRET_ACCESS_KEY=x
  - make test
notify:
  email:
    recipients:
      - drone@clever.com
  hipchat:
    room: Clever-Dev-CI
    token: {{hipchatToken}}
    on_started: true
    on_success: true
    on_failure: true
