image: bradrydzewski/go:1.3
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
script:
- go get github.com/tools/godep
- mkdir -p $GOPATH/src/github.com/Clever
- ln -s `pwd` $GOPATH/src/github.com/Clever/redshifter
- export AWS_ACCESS_KEY_ID=x
- export AWS_SECRET_ACCESS_KEY=x
- make test
