image: go1.4
notify:
  email:
    recipients:
    - drone@clever.com
publish:
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    image_name: clever/s3-to-redshift
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    username: $$docker_username
    when:
      branch: master
script:
  - make build
