image: go1.4
script:
  - mkdir -p $GOPATH/src/github.com/Clever
  - ln -s `pwd` $GOPATH/src/githuv.com/Clever/redshifter
  - make test
notify:
  email:
    recipients:
      - drone@clever.com
  hipchat:
    room: Clever-Dev-CI
    token: {{hipchatToken}}
    on_started: true
    on_success: true
    on_failure: true
