image: clever/drone-go:1.7
notify:
  email:
    recipients:
    - drone@clever.com
publish:
  catapult:
    url: $$catapult_url
    applications:
    - s3-to-redshift
    - s3-to-redshift-fast
    - s3-to-redshift-elb-logs
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    image_name: clever/s3-to-redshift
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    username: $$docker_username
    when:
      branch: master
  report_card: {}
script:
- make test
- make build
