image: clever/drone-go:1.5
notify:
  email:
    recipients:
    - drone@clever.com
publish:
  catapult:
    url: $$catapult_url
    application: "s3-to-redshift"
    when:
      branch: master
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    image_name: clever/s3-to-redshift
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    username: $$docker_username
    when:
      branch: master
script:
  - make build
