
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Clever/discovery-go"

[[constraint]]
  name = "github.com/Clever/pathio"

[[constraint]]
  name = "github.com/Clever/pq"

[[constraint]]
  branch = "master"
  name = "github.com/Clever/s3-to-redshift"

[[constraint]]
  name = "github.com/DATA-DOG/go-sqlmock"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  name = "github.com/kardianos/osext"

[[constraint]]
  name = "github.com/segmentio/go-env"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "6.2.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/clever/configure"
  version = "1.0.0"
