routes:
  job-finished:
    matchers:
      title: [ "job-finished" ]
    output:
      type: "alerts"
      series: "job.finished"
      dimensions: [ "source", "payload" ]
      value: "value"
      stat_type: "gauge"
